### ISSUE TITLE
Sanırım güncelliği yitirmiş bi bakarsan iyi olur 

### ISSUE THREAD

**Issue by upp4r** [xorcan/warp-plus-cloudflare#1]
İlk senin repoyu denedim çalışmadı ana repodan çekince oldu bi kontrol et istersen :)

**Comment by xorcan** [comment]
@upp4r düzeltildi kontrol eder misin

**Comment by upp4r** [comment]
kontrol ettim çalışıyor türkçeleştirmeler için de teşekkürler :)

**Comment by xorcan** [comment]
@upp4r rica ederim :)
